# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.dev                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pguthaus <pguthaus@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/18 19:17:34 by pguthaus          #+#    #+#              #
#    Updated: 2019/03/14 17:41:51 by pierre           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Sources sets
include make/srcs.mk
include make/test_srcs.mk
include make/config.mk

# Output name
NAME			=			libft_dev.a

TEST_NAME		=			tests_dev

# Compilation
CFLAGS			=			-g

# Paths
OUTDIR			=			./objs/dev/

# Test paths
TEST_OUTDIR		=			$(addprefix $(TEST_DIR), objs/dev/)

# OBJS
OBJS			=			$(addprefix $(OUTDIR),$(SRCS:.c=.o))
TEST_OBJS		=			$(addprefix $(TEST_OUTDIR),$(TEST_SRCS:.c=.o))

dev: $(NAME)

re: fclean $(NAME)

$(NAME): $(OBJS)
	@ar rcs $(NAME) $(OBJS)

$(OUTDIR)%.o: $(SRCDIR)%.c
	@if [ ! -d $(dir $@) ]; then mkdir -p $(dir $@); fi
	@$(CC) $(CFLAGS) -I $(INCDIR) -I $(MLX_INC) -o $@ -c $<

test: $(NAME) $(TEST_OBJS)
	@$(CC) $(CFLAGS) $(TEST_OBJS) $(NAME) $(MLX_ARGS) -o $(TEST_NAME) -lm

$(TEST_OUTDIR)%.o: $(TEST_SRCDIR)%.c
	@if [ ! -d $(dir $@) ]; then mkdir -p $(dir $@); fi
	@$(CC) $(CFLAGS) -I $(INCDIR) $(MLX_INC) -I $(TEST_INCDIR) -o $@ -c $<

clean:
	@rm -rf $(OUTDIR) $(TEST_OUTDIR)

fclean:
	@rm -rf $(NAME) $(TEST_NAME)*
